# Generated by Django 2.2.7 on 2019-12-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0002_flores_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flores',
            name='image',
        ),
    ]
